### ISSUE TITLE
[coladay]: relationtype vocabs include passageB_set

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#218]
not sure if this is only an issue with the coladay instance: some relationtype vocabs include a `passageB_set`, which should not be there. e.g.: https://sola.acdh-dev.oeaw.ac.at/apis/api/vocabularies/passagepassagerelation/

**Comment by sennierer** [comment]
Setting ```APIS_API_EXCLUDE_SETS = True``` should exclude all the _sets from the API

**Comment by steffres** [comment]
On the data model level, that is what we want: have a foreign key to all the entity instances a relationtype is instantiated with. This provides queries such as: give me all `persons` that are in any relation `where born in`.

However, on the API level, it's firstly debatable if want this, since it can grow big easily. Secondly even if we wanted it, it's weird that in this case only `personB_set` shows up. While for other cases such as https://sola.acdh-dev.oeaw.ac.at/apis/api/vocabularies/personpassagerelation/ no set is shown at all.

**Comment by steffres** [comment]
Alright, as Matthias just commented, it's possible to change it via settings. Though it's still weird that only one side of two possible ones show up. Can it be related to how the rest api wires up results @sennierer ?

**Comment by sennierer** [comment]
good point, in the init function of the endpoints we remove the _set fields here https://github.com/acdh-oeaw/apis-core/blob/02c51d4f7248c10162c49c91fe90ba922da63e60/apis_core/api_routers.py#L120-L124 if the setting mentioned before is set. Maybe this code is a bit different in the coladay instance?
