### ISSUE TITLE
Text API endpoint sometimes not returning text if highlight query parameter is set

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core#269]
curl "https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/1263/?highlight=true&inline_annotations=true" | jq

versus

curl "https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/1263/" | jq

**Comment by steffres** [comment]
further explanation from a message of mine earlier:

in coladay a text field is not delivered via REST API, namely this: https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/1263/?highlight=true&inline_annotations=true 
However when leaving out the params, then the text field is returned https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/1263 or when leaving out only the `highlight` param and keep the `inline_annotations` https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/1263/?inline_annotations=true

The `highlight` param is handled here I assume: https://gitlab.com/acdh-oeaw/apis/apis-core/-/blob/master/apis_core/api_routers.py#L351 What is it for anyway? To indicate if a text has a highlighted part? If so then this fails, because it has a highlight done here: https://sola.acdh-dev.oeaw.ac.at/apis/entities/entity/passage/881/edit on the latin text starting with `12. Οὗτος ἀκούσας ...`

**Comment by stefanprobst** [comment]
looks like this is resolved?
