### ISSUE TITLE
can’t enter negative dates

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/apis-core#60]
**Description:** When trying to enter a negtaive start or end date for a work entity, on save I get an error message: Please enter a valide date: (DD).(MM).YYYY 

**How to reproduce:**
* go to https://coladay.acdh-dev.oeaw.ac.at/apis/entities/entity/work/create
* enter a dummy name
* enter -0123 as start date and -0120 as end date

**Comment by skurzinz** [comment]
Together with [https://github.com/acdh-oeaw/apis-core/issues/56](#56) perhaps reformulate the question to "what is a valid date for APIS" and "what is the date spectrum we want to be able to depict"? 

Things to consider: 

- BC dates (likely that's what @dasch124 is referring to)
- ways of recalculating alternative calendars to conform to that dd.mm.yyyy scheme ([https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-calendar.html](TEI `calendar`) has a few examples; as has [https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.datable.custom.html](TEI `att.datable.custom`)
- fuzziness (TEI @notBefore/@notAfter and the like)
I’m thinking TEI since that is the primary usecase for us in exporting datable entities/relations for INZ…

**Comment by csae8092** [comment]
The (date) forms displayed in the edit views are actually simple text forms (for "written dates"). Though on save, APIS tries to parse the entered strings into a valid date format which will then be stored in (for the user hidden) normalized date fields. This obviously doesn't work for complex dates/string.
Possible solutions:
* make the parsing more tolerant and in case it the strings can't be parsed, save only the "written dates"
* same as above but also display the currently hidden date fields to the user, so users can enter normalized dates by themselves. On save, if the normalized date field is empty, try to parse the "written date" if this works, save the normlized date, if not, leave the normlized date blank

I'd go for the latter version, because it is the most transparent and users can modify the normalized dates.

**Comment by sennierer** [comment]
agree. though we could also (to keep things simple in the GUI) add a simple javascript that just calls the normalizer function on the backend and updates the help text of the field with the parsed date. Like that people always know what will end in the db, but we dont have the hassles with two editable fields that shoule be in sync (e.g. what to do when they edit both fields at the same time, which one to save etc).
