### ISSUE TITLE
GND Import – Profession, place of birth?, date

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#86]
The automatic import of GND-entitities is flawed:
* it skips the professions
* it skips the gender
* it imports "1920" (without day and month) as "1920-01-01"
* I could not check but I'm quite sure it does not import place of birth and place of death

**Comment by sennierer** [comment]
the import from GND is configureable.

I need to check how it is set on PMB, but I am pretty sure it imports place of birth and death. Could be though that we are not importing gender and profession.

it is 1920-1-1 because that is the sortdate computed from 1920. we still have the original string (1920) stored in the db though.

**Comment by martinantonmueller** [comment]
you're right, just checked, place of birth and death are imported. but I don't think the 1920-thing is correct (or it doesn't show me the literal date even when I select it)

**Comment by sennierer** [comment]
could you please provide an example?

**Comment by martinantonmueller** [comment]
Easy. Use the "Import new Person from GND" feature and add me (Müller, Martin Anton, my GND Number: 1050382196). GND knows I was born in 1977 but doesn't know day and month. Nevertheless you'll see that it will be stored as 1.1.1977
